### ISSUE TITLE
1 - App name?

### ISSUE THREAD

**Issue by AlvanMO** [Natels/Twenty8Two#1]
Do we use - 
- Twenty8two
or
- 20eight2

Both names are currently not used in the Apple Store or Chrome Web Store.

**Comment by Natels** [comment]
I like both. Twenty8Two can follow pascal or camelCasing rules when inside the code but 20eight2 is shorter and more pleasant visually. I suggest we use the first within the logic of the code but wherever it will be displayed to the user it will be the second. Could be nice to have a quick way to tell those references apart anyways.
